Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd     = os.path.join(str(Dir('#')), 'apps')
src	= Glob('*.c')
CPPPATH = [cwd, str(Dir('#')),cwd+'/utils']

src += [cwd+'/utils/utils.c']

group = DefineGroup('Apps', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
