Import('RTT_ROOT')
Import('rtconfig')
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
JSON_parser.c
ping.c
url_parse.c
webclient.c
""")

path = [cwd]

group = DefineGroup('WebUtils', src, depend = [''], CPPPATH = path)

Return('group')
